### ISSUE TITLE
Toggl deprecating old API July 2021

### ISSUE THREAD

**Issue by matt-in-a-hat** [smeggingsmegger/PyToggl#2]
Looks like this is using the old API, which sounds like will no longer be supported in July 2021.

From Toggl:
After last year's rebranding, we released api.track.toggl.com as our new domain for API usage. These changes were communicated via newsletter and [the following blog post](https://toggl.com/blog/api-documentation-change). [The API Docs](https://github.com/toggl/toggl_api_docs) were also updated to reflect the domain changes.

We want to inform you that the usage of www.toggl.com(or toggl.com) domain for the API will be dropped after 'June 30th 2021'.

**Comment by smeggingsmegger** [comment]
Looks like Brad got this one in his PR: https://github.com/smeggingsmegger/PyToggl/pull/3

**Comment by matt-in-a-hat** [comment]
Awesome, @smeggingsmegger are you able to push a release/tag to pip?
